id: hl7.fhir.uganda.core
canonical: http://fhir.health.go.ug
name: Uganda-Core-FHIR-IG
title: UGANDA FHIR IMPLEMENETATION IG
description: Uganda Health Information Exchange FHIR Implementation Guide
status: draft
version: 1.1.0
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ci-build
publisher:
  name: Ministry of Health Uganda
  url: https://www.health.go.ug
  email: info@health.go.ug

menu:
  Home: index.html
  Artifacts: artifacts.html

instanceOptions:
  # When set to true, slices must be referred to by name and not only by a numeric index in order to be used
  # in an Instance's assignment rule. All slices appear in the order in which they are specified in FSH rules.
  # While SUSHI defaults to false for legacy reasons, manualSliceOrding is recommended for new projects.
  manualSliceOrdering: true # true | false